In [1]:
import pandas as pd
import tiktoken

In [2]:
df = pd.read_csv("grasp_results/results.csv")
df

,index,energy,energy_probability,obstacle,start_position,input_prompt,response,method,model,dataset_name,model_name,returns_to_start,invalid_move,valid
0,0,-2.0,4.000000,block,inner,system: You are a helpful assistant.\nuser: \n...,I notice there's a discrepancy in the updated ...,2_step,anthropic/claude-3.7-sonnet,inner_cluster_block,anthropic-claude-3.7-sonnet,False,False,True
1,1,-2.0,4.000000,block,inner,system: You are a helpful assistant.\nuser: \n...,I notice there was a misunderstanding in the p...,2_step,anthropic/claude-3.7-sonnet,inner_cluster_block,anthropic-claude-3.7-sonnet,False,False,True
2,2,-4.0,3.000000,block,inner,system: You are a helpful assistant.\nuser: \n...,I notice there's a discrepancy in the updated ...,2_step,anthropic/claude-3.7-sonnet,inner_cluster_block,anthropic-claude-3.7-sonnet,False,False,True
3,3,-3.0,5.000000,block,inner,system: You are a helpful assistant.\nuser: \n...,I notice there seems to be a misunderstanding....,2_step,anthropic/claude-3.7-sonnet,inner_cluster_block,anthropic-claude-3.7-sonnet,False,False,True
4,4,-4.0,4.000000,block,inner,system: You are a helpful assistant.\nuser: \n...,I notice there's a discrepancy in the feedback...,2_step,anthropic/claude-3.7-sonnet,inner_cluster_block,anthropic-claude-3.7-sonnet,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,5,-0.2,0.301958,free,inner,system: You are a helpful assistant.\nuser: \n...,"<final_answer>\n [""DOWN"", ""TAKE"", ""LEFT"", ""...",direct,openai/o3-mini,inner_upDown_free,openai-o3-mini,True,False,True
1196,6,-0.7,0.316379,free,inner,system: You are a helpful assistant.\nuser: \n...,"<final_answer>\n [""RIGHT"", ""TAKE"", ""DOWN"", ...",direct,openai/o3-mini,inner_upDown_free,openai-o3-mini,True,False,True
1197,7,-1.0,0.693346,free,inner,system: You are a helpful assistant.\nuser: \n...,"<final_answer>\n [""LEFT"", ""TAKE"", ""DOWN"", ""...",direct,openai/o3-mini,inner_upDown_free,openai-o3-mini,True,False,True
1198,8,-1.1,0.326402,free,inner,system: You are a helpful assistant.\nuser: \n...,"<final_answer>\n [""LEFT"", ""TAKE"", ""DOWN"", ""...",direct,openai/o3-mini,inner_upDown_free,openai-o3-mini,True,False,True
1199,9,-1.4,0.397227,free,inner,system: You are a helpful assistant.\nuser: \n...,"<final_answer>\n [""DOWN"", ""TAKE"", ""UPRIGHT""...",direct,openai/o3-mini,inner_upDown_free,openai-o3-mini,True,False,True

In [3]:
def get_input_text(row):
    if row['method'] != '2_step':
        return row['input_prompt']
    
    return row['input_prompt'].split("assistant:")[0] + "\n" + row['input_prompt']

In [4]:
def get_output_text(row):
    if row['method'] != '2_step':
        return row['response']
    
    return row['input_prompt'].split("assistant:")[1].split("user:")[0] + "\n" + row['response']

In [5]:
def get_num_tokens(text):
    enc = tiktoken.encoding_for_model("gpt-4o")
    try:
        tokens = enc.encode(text)
    except Exception as e:
        print(f"Error encoding text: {text}... Error: {e}")
        return 0
    return len(tokens)

In [6]:
MODEL_COSTS = {
    'openai-gpt-4o': (2.5, 10),
    'openai-o3-mini': (1.1, 4.4),
    'anthropic-claude-3.7-sonnet': (3, 15),
    'google-gemini-2.5-pro': (1.25, 10),
}

In [7]:
df['input_text_total'] = df.apply(lambda row: get_input_text(row), axis=1)
df['output_text_total'] = df.apply(lambda row: get_output_text(row), axis=1)
df['input_text_tokens'] = df.apply(lambda row: get_num_tokens(row['input_text_total']), axis=1)
df['output_text_tokens'] = df.apply(lambda row: get_num_tokens(row['output_text_total']), axis=1)
df['input_cost'] = df.apply(lambda row: row['input_text_tokens'] * MODEL_COSTS[row['model_name']][0] / 1e6, axis=1)
df['output_cost'] = df.apply(lambda row: row['output_text_tokens'] * MODEL_COSTS[row['model_name']][1] / 1e6, axis=1)
df['total_cost'] = df['input_cost'] + df['output_cost']

Error encoding text: nan... Error: expected string or buffer

In [8]:
df.groupby(['model_name', 'method'])['energy'].describe()[['mean', 'std']].round(2)

                                    mean   std
model_name                  method
anthropic-claude-3.7-sonnet 2_step -3.70  1.25
                            cot    -4.00  1.55
                            direct -3.72  1.54
google-gemini-2.5-pro       2_step -1.11  0.78
                            cot    -0.95  1.06
                            direct -0.85  0.86
openai-gpt-4o               2_step -3.10  1.51
                            cot    -2.12  1.40
                            direct -1.66  1.46
openai-o3-mini              2_step -1.91  1.00
                            cot    -1.03  0.77
                            direct -0.97  0.66

In [9]:
df[df.total_cost > 0].groupby(['model_name', 'method'])['total_cost'].mean()

model_name                   method
anthropic-claude-3.7-sonnet  2_step    0.020638
                             cot       0.011465
                             direct    0.011627
google-gemini-2.5-pro        2_step    0.013611
                             cot       0.011547
                             direct    0.010292
openai-gpt-4o                2_step    0.014572
                             cot       0.007954
                             direct    0.006579
openai-o3-mini               2_step    0.003926
                             cot       0.001987
                             direct    0.001796
Name: total_cost, dtype: float64

In [10]:
minigrid_df = pd.read_csv("minigrid_results/results.csv")
minigrid_df

,task,seed,method,model,start_direction,input_prompt,response,model_name,reward,done,valid
0,door_key,0,2_step,anthropic/claude-3.7-sonnet,DOWN,system: You are a helpful assistant.\nuser: \n...,I notice there's an issue with the updated gri...,anthropic-claude-3.7-sonnet,0.000000,False,True
1,door_key,1,2_step,anthropic/claude-3.7-sonnet,UP,system: You are a helpful assistant.\nuser: \n...,Now I need to complete the task by unlocking t...,anthropic-claude-3.7-sonnet,0.000000,False,True
2,door_key,10,2_step,anthropic/claude-3.7-sonnet,RIGHT,system: You are a helpful assistant.\nuser: \n...,I see the updated grid. I'm now at position [3...,anthropic-claude-3.7-sonnet,0.000000,False,True
3,door_key,11,2_step,anthropic/claude-3.7-sonnet,RIGHT,system: You are a helpful assistant.\nuser: \n...,Now I need to complete the task by going throu...,anthropic-claude-3.7-sonnet,0.000000,False,True
4,door_key,12,2_step,anthropic/claude-3.7-sonnet,RIGHT,system: You are a helpful assistant.\nuser: \n...,I see the updated grid. I'm now at position [4...,anthropic-claude-3.7-sonnet,0.000000,False,True
...,...,...,...,...,...,...,...,...,...,...,...
3591,unlock_pickup,95,direct,openai/o3-mini,DOWN,system: You are a helpful assistant.\nuser: \n...,"<actions>\n [""RIGHT"", ""MOVE"", ""MOVE"", ""RIGH...",openai-o3-mini,0.937500,True,True
3592,unlock_pickup,96,direct,openai/o3-mini,UP,system: You are a helpful assistant.\nuser: \n...,"<actions>\n [""RIGHT"", ""MOVE"", ""PICKUP"", ""MO...",openai-o3-mini,0.940625,True,True
3593,unlock_pickup,97,direct,openai/o3-mini,RIGHT,system: You are a helpful assistant.\nuser: \n...,"<actions>\n[""MOVE"", ""MOVE"", ""PICKUP"", ""MOVE"", ...",openai-o3-mini,0.953125,True,True
3594,unlock_pickup,98,direct,openai/o3-mini,RIGHT,system: You are a helpful assistant.\nuser: \n...,"<actions>\n [""LEFT"", ""MOVE"", ""LEFT"", ""PICKU...",openai-o3-mini,0.946875,True,True
3595,unlock_pickup,99,direct,openai/o3-mini,DOWN,system: You are a helpful assistant.\nuser: \n...,"<actions>\n [""LEFT"", ""LEFT"", ""MOVE"", ""PICKU...",openai-o3-mini,0.000000,False,True

In [11]:
minigrid_df['task'].value_counts()

task
unlock_pickup    1200
unlock           1199
door_key         1197
Name: count, dtype: int64

In [12]:
minigrid_df['input_text_total'] = minigrid_df.apply(lambda row: get_input_text(row), axis=1)
minigrid_df['output_text_total'] = minigrid_df.apply(lambda row: get_output_text(row), axis=1)
minigrid_df['input_text_tokens'] = minigrid_df.apply(lambda row: get_num_tokens(row['input_text_total']), axis=1)
minigrid_df['output_text_tokens'] = minigrid_df.apply(lambda row: get_num_tokens(row['output_text_total']), axis=1)
minigrid_df['input_cost'] = minigrid_df.apply(lambda row: row['input_text_tokens'] * MODEL_COSTS[row['model_name']][0] / 1e6, axis=1)
minigrid_df['output_cost'] = minigrid_df.apply(lambda row: row['output_text_tokens'] * MODEL_COSTS[row['model_name']][1] / 1e6, axis=1)
minigrid_df['total_cost'] = minigrid_df['input_cost'] + minigrid_df['output_cost']

Error encoding text: nan... Error: expected string or buffer

In [13]:
minigrid_df.groupby(['model_name', 'task', 'method'])['reward'].mean()

model_name                   task           method
anthropic-claude-3.7-sonnet  door_key       2_step    0.019791
                                            cot       0.000000
                                            direct    0.000000
                             unlock         2_step    0.048422
                                            cot       0.038344
                                            direct    0.038406
                             unlock_pickup  2_step    0.000000
                                            cot       0.000000
                                            direct    0.000000
google-gemini-2.5-pro        door_key       2_step    0.761353
                                            cot       0.868189
                                            direct    0.896976
                             unlock         2_step    0.900219
                                            cot       0.880969
                                            direct    0.928375
                             unlock_pickup  2_step    0.535625
                                            cot       0.545594
                                            direct    0.516437
openai-gpt-4o                door_key       2_step    0.019325
                                            cot       0.000000
                                            direct    0.000000
                             unlock         2_step    0.086625
                                            cot       0.105969
                                            direct    0.086219
                             unlock_pickup  2_step    0.000000
                                            cot       0.000000
                                            direct    0.000000
openai-o3-mini               door_key       2_step    0.965784
                                            cot       0.946291
                                            direct    0.956038
                             unlock         2_step    0.967969
                                            cot       0.967656
                                            direct    0.968125
                             unlock_pickup  2_step    0.835125
                                            cot       0.479531
                                            direct    0.527313
Name: reward, dtype: float64

In [14]:
# minigrid_df = minigrid_df[minigrid_df['method'] != 'direct']

In [15]:
minigrid_df.groupby(['model_name', 'task', 'method'])['reward'].describe()[['mean', 'std']].round(2)

                                                  mean   std
model_name                  task          method
anthropic-claude-3.7-sonnet door_key      2_step  0.02  0.14
                                          cot     0.00  0.00
                                          direct  0.00  0.00
                            unlock        2_step  0.05  0.21
                                          cot     0.04  0.19
                                          direct  0.04  0.19
                            unlock_pickup 2_step  0.00  0.00
                                          cot     0.00  0.00
                                          direct  0.00  0.00
google-gemini-2.5-pro       door_key      2_step  0.76  0.41
                                          cot     0.87  0.31
                                          direct  0.90  0.27
                            unlock        2_step  0.90  0.25
                                          cot     0.88  0.28
                                          direct  0.93  0.19
                            unlock_pickup 2_step  0.54  0.47
                                          cot     0.55  0.47
                                          direct  0.52  0.47
openai-gpt-4o               door_key      2_step  0.02  0.14
                                          cot     0.00  0.00
                                          direct  0.00  0.00
                            unlock        2_step  0.09  0.28
                                          cot     0.11  0.30
                                          direct  0.09  0.28
                            unlock_pickup 2_step  0.00  0.00
                                          cot     0.00  0.00
                                          direct  0.00  0.00
openai-o3-mini              door_key      2_step  0.97  0.10
                                          cot     0.95  0.17
                                          direct  0.96  0.14
                            unlock        2_step  0.97  0.01
                                          cot     0.97  0.01
                                          direct  0.97  0.01
                            unlock_pickup 2_step  0.84  0.30
                                          cot     0.48  0.47
                                          direct  0.53  0.47

In [16]:
minigrid_df.groupby(['model_name', 'task', 'method'])['total_cost'].mean().round(3)

model_name                   task           method
anthropic-claude-3.7-sonnet  door_key       2_step    0.013
                                            cot       0.006
                                            direct    0.005
                             unlock         2_step    0.011
                                            cot       0.005
                                            direct    0.005
                             unlock_pickup  2_step    0.014
                                            cot       0.006
                                            direct    0.006
google-gemini-2.5-pro        door_key       2_step    0.003
                                            cot       0.009
                                            direct    0.002
                             unlock         2_step    0.003
                                            cot       0.009
                                            direct    0.002
                             unlock_pickup  2_step    0.005
                                            cot       0.008
                                            direct    0.004
openai-gpt-4o                door_key       2_step    0.018
                                            cot       0.007
                                            direct    0.007
                             unlock         2_step    0.009
                                            cot       0.008
                                            direct    0.006
                             unlock_pickup  2_step    0.016
                                            cot       0.011
                                            direct    0.007
openai-o3-mini               door_key       2_step    0.002
                                            cot       0.003
                                            direct    0.002
                             unlock         2_step    0.002
                                            cot       0.002
                                            direct    0.001
                             unlock_pickup  2_step    0.003
                                            cot       0.003
                                            direct    0.002
Name: total_cost, dtype: float64

In [17]:
# minigrid_df.groupby(['task', 'method'])['done'].mean()